steps:
  - label: ":swift: Build & Run"
    commands:
      # - "echo '+++ :swift: Build'"
      - "echo -e '+++ \033[35m:swift: Building the Swift project\033[0m'" # Blue for build group header
      - "swift build"
      - "echo '+++ :swift: Run'"
      - "swift run"
    agents:
      queue: hosted-macos-medium
