steps:
  - label: ":swift: Ignore cache"
    key: "spm-cache-ignore"
    commands:
      - ".buildkite/steps/cache.sh ignore"
    agents:
      queue: hosted-macos-medium
      nsc-cache-tag: "spm-cache"

  - label: ":swift: Resolve cache"
    key: "spm-cache-resolve"
    commands:
      - ".buildkite/steps/cache.sh resolve"
    agents:
      queue: hosted-macos-medium
      nsc-cache-tag: "spm-cache"

  - label: ":swift: Clear cache"
    key: "spm-cache-clear"
    commands:
      - ".buildkite/steps/cache.sh clear"
    agents:
      queue: hosted-macos-medium
      nsc-cache-tag: "spm-cache"
    depends_on: "spm-cache-resolve"

  - label: ":swift: Resolve cache again"
    key: "spm-cache-resolve-again"
    commands:
      - ".buildkite/steps/cache.sh resolve"
    agents:
      queue: hosted-macos-medium
      nsc-cache-tag: "spm-cache"
    depends_on: "spm-cache-clear"

  - label: ":swift: Rebuild cache"
    key: "spm-cache-rebuild"
    commands:
      - ".buildkite/steps/cache.sh rebuild"
    agents:
      queue: hosted-macos-medium
      nsc-cache-tag: "spm-cache"
    depends_on: "spm-cache-resolve-again"

  - label: ":swift: Resolve cache again again"
    key: "spm-cache-resolve-again-again"
    commands:
      - ".buildkite/steps/cache.sh resolve"
    agents:
      queue: hosted-macos-medium
      nsc-cache-tag: "spm-cache"
    depends_on: "spm-cache-rebuild"

  # - label: ":swift: Resolve Dependencies (with cache)"
  #   key: "resolve-dependencies-with-cache"
  #   command: ".buildkite/steps/resolve-dependencies.sh"
  #   agents:
  #     queue: hosted-macos-medium
  #     nsc-cache-tag: "package-cache"
  #   env:
  #     USE_CACHE: "true"
  #     CACHE_KEY: "${BUILDKITE_BRANCH}" # Placeholder only (for now)

  # - label: ":swift: Resolve Dependencies (no cache)"
  #   key: "resolve-dependencies-no-cache"
  #   command: ".buildkite/steps/resolve-dependencies.sh"
  #   agents:
  #     queue: hosted-macos-medium
  #     nsc-cache-tag: "package-cache"
  #   env:
  #     USE_CACHE: "false"
  #     CACHE_KEY: "${BUILDKITE_BRANCH}" # Placeholder only (for now)

  # # Resolve Dependencies with Cache
  # - label: ":swift: Resolve Dependencies (with cache)"
  #   key: "resolve-dependencies-with-cache"
  #   command: ".buildkite/steps/resolve-dependencies-with-cache.sh"
  #   agents:
  #     queue: hosted-macos-medium
  #     nsc-cache-tag: "package-cache"

  # # Build Project with Cache
  # - label: ":swift: Build Project (with cache)"
  #   key: "build-project-with-cache"
  #   command: ".buildkite/steps/build-project-with-cache.sh"
  #   agents:
  #     queue: hosted-macos-medium
  #     nsc-cache-tag: "package-cache"
  #   depends_on: "resolve-dependencies-with-cache"

  # # Resolve Dependencies without Cache
  # - label: ":swift: Resolve Dependencies (no cache)"
  #   key: "resolve-dependencies-no-cache"
  #   command: ".buildkite/steps/resolve-dependencies-no-cache.sh"
  #   agents:
  #     queue: hosted-macos-medium

  # # Build Project without Cache
  # - label: ":swift: Build Project (no cache)"
  #   key: "build-project-no-cache"
  #   command: ".buildkite/steps/build-project-no-cache.sh"
  #   agents:
  #     queue: hosted-macos-medium
  #   depends_on:
  #     - "resolve-dependencies-no-cache"
