steps:
  - label: ":swift: Resolve Dependencies (with cache)"
    key: "resolve-dependencies-with-cache"
    commands:
      - "echo -e '+++ \\033[35m:swift: Restoring cached dependencies\\033[0m'"
      - "if [ -d $NSC_CACHE_PATH/build ]; then cp -a $NSC_CACHE_PATH/build ./.build 2>&1 | grep -v 'No such file or directory' || true; fi" # Use cache from /Volumes/cache
      - "echo -e '+++ \\033[36m:swift: Resolving Swift package dependencies\\033[0m'"
      - "swift package resolve"
      - "echo -e '+++ \\033[32m:swift: Caching resolved dependencies\\033[0m'"
      - "mkdir -p $NSC_CACHE_PATH/build && cp -a ./.build $NSC_CACHE_PATH/build 2>&1 | grep -v 'No such file or directory' || true" # Cache to /Volumes/cache
    agents:
      queue: hosted-macos-medium
      nsc-cache-tag: "package-cache"

  - label: ":swift: Build Project (with cache)"
    key: "build-project-with-cache"
    commands:
      - "echo -e '+++ \\033[35m:swift: Restoring cached build artifacts\\033[0m'"
      - "if [ -d $NSC_CACHE_PATH/build ]; then cp -a $NSC_CACHE_PATH/build ./.build 2>&1 | grep -v 'No such file or directory' || true; fi" # Restore cache from /Volumes/cache
      - "echo -e '+++ \\033[36m:swift: Building the Swift project\\033[0m'"
      - "swift build"
      - "echo -e '+++ \\033[32m:swift: Caching build artifacts\\033[0m'"
      - "mkdir -p $NSC_CACHE_PATH/build && cp -a ./.build $NSC_CACHE_PATH/build 2>&1 | grep -v 'No such file or directory' || true" # Cache to /Volumes/cache
    agents:
      queue: hosted-macos-medium
      nsc-cache-tag: "package-cache"
    depends_on:
      - "resolve-dependencies-with-cache"

  - label: ":swift: Resolve Dependencies (no cache)"
    key: "resolve-dependencies-no-cache"
    commands:
      - "echo -e '+++ \\033[36m:swift: Resolving Swift package dependencies (no cache)\\033[0m'"
      - "swift package resolve"
    agents:
      queue: hosted-macos-medium

  - label: ":swift: Build Project (no cache)"
    key: "build-project-no-cache"
    commands:
      - "echo -e '+++ \\033[36m:swift: Building the Swift project (no cache)\\033[0m'"
      - "swift build"
    agents:
      queue: hosted-macos-medium
    depends_on:
      - "resolve-dependencies-no-cache"
