steps:
  - label: ":swift: New cache script"
    key: "new-cache-script"
    commands:
      - ".buildkite/steps/new-cache-script.sh resolve"
      # - ".buildkite/steps/new-cache-script.sh ignore"
      # - ".buildkite/steps/new-cache-script.sh clear"
    agents:
      queue: hosted-macos-medium
      nsc-cache-tag: "spm-cache" # Is this the cache key?


  # - label: ":swift: Resolve Dependencies (with cache)"
  #   key: "resolve-dependencies-with-cache"
  #   command: ".buildkite/steps/resolve-dependencies.sh"
  #   agents:
  #     queue: hosted-macos-medium
  #     nsc-cache-tag: "package-cache" # Is this the cache key?
  #   env:
  #     USE_CACHE: "true"
  #     CACHE_KEY: "${BUILDKITE_BRANCH}" # Placeholder only (for now)

  # - label: ":swift: Resolve Dependencies (no cache)"
  #   key: "resolve-dependencies-no-cache"
  #   command: ".buildkite/steps/resolve-dependencies.sh"
  #   agents:
  #     queue: hosted-macos-medium
  #     nsc-cache-tag: "package-cache" # Is this the cache key?
  #   env:
  #     USE_CACHE: "false"
  #     CACHE_KEY: "${BUILDKITE_BRANCH}" # Placeholder only (for now)

  # # Resolve Dependencies with Cache
  # - label: ":swift: Resolve Dependencies (with cache)"
  #   key: "resolve-dependencies-with-cache"
  #   command: ".buildkite/steps/resolve-dependencies-with-cache.sh"
  #   agents:
  #     queue: hosted-macos-medium
  #     nsc-cache-tag: "package-cache"

  # # Build Project with Cache
  # - label: ":swift: Build Project (with cache)"
  #   key: "build-project-with-cache"
  #   command: ".buildkite/steps/build-project-with-cache.sh"
  #   agents:
  #     queue: hosted-macos-medium
  #     nsc-cache-tag: "package-cache"
  #   depends_on: "resolve-dependencies-with-cache"

  # # Resolve Dependencies without Cache
  # - label: ":swift: Resolve Dependencies (no cache)"
  #   key: "resolve-dependencies-no-cache"
  #   command: ".buildkite/steps/resolve-dependencies-no-cache.sh"
  #   agents:
  #     queue: hosted-macos-medium

  # # Build Project without Cache
  # - label: ":swift: Build Project (no cache)"
  #   key: "build-project-no-cache"
  #   command: ".buildkite/steps/build-project-no-cache.sh"
  #   agents:
  #     queue: hosted-macos-medium
  #   depends_on:
  #     - "resolve-dependencies-no-cache"
