steps:
  - label: ":swift: Build & Run"
    commands:
      - "echo -e '+++ \033[34m:swift: Building the Swift project\033[0m'"
      - "swift build"
      - "echo -e '+++ \033[35m:swift: Running the Swift script\033[0m'"
      - "swift run"
    agents:
      queue: hosted-macos-medium
